/**
 * @swagger
 *  tags:
 *      name: Users
 */

/**
 * @swagger
 * /api/register:
 * 
 *  post:
 *      summary: Register an account
 *      operationId: register
 *      tags: [Users]
 *      requestBody:
 *          content:
 *              application/json:
 *                  schema:
 *                      type: object
 *                      properties:
 *                          email: 
 *                              type: string
 *                          password: 
 *                              type: string
 *                          name: 
 *                              type: string
 *                          height:
 *                              type: integer
 *                          weight:
 *                              type: integer
 *                          age:
 *                              type: integer
 *                  example:
 *                      email: renaldy123@gmail.com
 *                      password: renaldy123
 *                      name: renaldy permana
 *                      height: 175
 *                      weight: 60
 *                      age: 20
 *      responses:
 *          200:
 *              description: Return the user on success
 *              content:
 *                  application/json:
 *                      schema:
 *                          type: object
 *                          properties:
 *                              data:
 *                                  id:
 *                                      type: string
 *                                  email: 
 *                                      type: string
 *                                  password: 
 *                                      type: string
 *                                  name: 
 *                                      type: string
 *                                  height:
 *                                      type: integer
 *                                  weight:
 *                                      type: integer
 *                                  age:
 *                                      type: integer
 *                      example:
 *                          data:
 *                              id: cm3ylo2u000003j6ig5daov53
 *                              email: renaldy123@gmail.com
 *                              password: renaldy123
 *                              name: renaldy permana
 *                              height: 175
 *                              weight: 60
 *                              age: 20
 */

/**
 * @swagger
 * /api/login:
 * 
 *  post:
 *      summary: Login an account
 *      operationId: login
 *      tags: [Users]
 *      requestBody:
 *          content:
 *              application/json:
 *                  schema:
 *                      type: object
 *                      properties:
 *                          email: 
 *                              type: string
 *                          password: 
 *                              type: string
 *                  example:
 *                      email: renaldy123@gmail.com
 *                      password: renaldy123
 *      responses:
 *          200:
 *              description: Return the user on success
 *              content:
 *                  application/json:
 *                      schema:
 *                          type: object
 *                          properties:
 *                              data:
 *                                  id: 
 *                                      type: string
 *                                      description: ID of the user
 *                                  email: 
 *                                      type: string
 *                                      description: email of the user
 *                                  access_token: 
 *                                      type: string
 *                                      description: token generated by JWT
 *                      example:
 *                          data:
 *                              id: cm3ylo2u000003j6ig5daov53
 *                              email: renaldy123@gmail.com
 *                              access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtM3ludzN6bjAwMDB3Y3RjZXFzbWd2eHoiLCJlbWFpbCI6InJlbmFsZHkxMjNAZ21haWwuY29tIiwiaWF0IjoxNzMyNjM3OTU0LCJleHAiOjE3MzI2NDE1NTR9.lXhNgi11ga4qRoRd7sy02txobvd7_KeOqVcvIyQv83w
 */

/**
 * @swagger
 * /api/users/current:
 * 
 *  get:
 *      security:
 *      - bearerAuth: []
 *      summary: Get current user
 *      operationId: get-current-user
 *      tags: [Users]
 * 
 *      responses:
 *          200:
 *              description: Return the user on success
 *              content:
 *                  application/json:
 *                      schema:
 *                          type: object
 *                          properties:
 *                              data:
 *                                  id:
 *                                      type: string
 *                                      description: ID of the current user
 *                                  email:
 *                                      type: string
 *                                      description: email of the current user
 *                      example:
 *                          data:
 *                              id: cm3ylo2u000003j6ig5daov53
 *                              email: renaldy123@gmail.com
 */

/**
 * @swagger
 * /api/users/current:
 * 
 *  patch:
 *      security:
 *      - bearerAuth: []
 *      summary: Update user password
 *      operationId: update-password
 *      tags: [Users]
 *      requestBody:
 *          content:
 *              application/json:
 *                  schema:
 *                      type: object
 *                      properties:
 *                          password:
 *                              type: string
 *                              description: new user password
 *                  example:
 *                      password: renaldy321
 *      responses:
 *          200:
 *              description: Return the user on success
 *              content:
 *                  application/json:
 *                      schema:
 *                          type: object
 *                          properties:
 *                              data:
 *                                  id:
 *                                      type: string
 *                                      description: ID of the current user
 *                                  email:
 *                                      type: string
 *                                      description: email of the current user
 * 
 *                      example:
 *                          data:
 *                              id: cm3ylo2u000003j6ig5daov53
 *                              email: renaldy123@gmail.com
 */